"""DailyReport domain model.

A DailyReport is the primary published output of the Sentinel platform —
an intelligence brief assembled from MarketEvents and Articles collected
during the coverage window.
"""

from __future__ import annotations

from datetime import UTC, date, datetime, timedelta
import uuid

from pydantic import Field, field_validator, model_validator

from sentinel_core.enums import ReportStatus, ReportType
from sentinel_core.models._base import SentinelModel

_MAX_FUTURE_COVERAGE_DAYS = 7


class DailyReport(SentinelModel):
    """A single published intelligence brief for a given coverage date.

    DailyReports are the unit of output that end investors consume. One report
    is produced per scheduled pipeline run. Reports are assembled from
    ReportSections, each covering a different market segment.

    Uniqueness constraints (enforced at the database layer):
        - (coverage_date, report_type) must be unique. Only one Daily Brief
          may exist per calendar date.

    Note on circular dependency with PipelineRun:
        DailyReport holds a nullable pipeline_run_id FK. PipelineRun holds a
        nullable daily_report_id FK. The application layer sets both sides after
        both records exist. See contracts §6 for rationale.

    Validation rules:
        - published_at must be None when status is not PUBLISHED.
        - notion_page_id must be None when status is not PUBLISHED.
        - article_count and event_count must be >= 0.
        - coverage_date must not be more than 7 days in the future.

    Fields:
        id: UUID v4 primary key.
        report_type: Format and cadence; defaults to DAILY_BRIEF.
        status: Publication state; defaults to DRAFT.
        coverage_date: Calendar date this report covers (date, not datetime).
        title: Report headline; max 300 chars. Set by the intelligence layer.
        executive_summary: Top-line 3-5 sentence summary; max 2000 chars.
        pipeline_run_id: FK to the generating PipelineRun. Optional.
        article_count: Total articles ingested in the coverage window (>= 0).
        event_count: Total MarketEvents synthesised for this report (>= 0).
        published_at: UTC publication timestamp. None until status=PUBLISHED.
        notion_page_id: Notion page ID after publication; max 100 chars.
        error_message: Set when status=FAILED; max 2000 chars.
        created_at: UTC construction timestamp.
        updated_at: UTC last-mutation timestamp.

    Example::

        DailyReport(coverage_date=date(2026, 8, 7))
    """

    report_type: ReportType = Field(
        default=ReportType.DAILY_BRIEF,
        description="Format and cadence of this report.",
    )
    status: ReportStatus = Field(
        default=ReportStatus.DRAFT,
        description="Current publication state of this report.",
    )
    coverage_date: date = Field(
        description=(
            "Calendar date this report covers. "
            "Must not be more than 7 days in the future. "
            "Unique per report_type (enforced at the database layer)."
        ),
    )
    title: str | None = Field(
        default=None,
        max_length=300,
        description="Report headline. Auto-generated by the intelligence layer.",
    )
    executive_summary: str | None = Field(
        default=None,
        max_length=2000,
        description="Top-line 3-5 sentence summary across all report sections.",
    )
    pipeline_run_id: uuid.UUID | None = Field(
        default=None,
        description="FK to the PipelineRun that generated this report.",
    )
    article_count: int = Field(
        default=0,
        ge=0,
        description="Total articles ingested in this report's coverage window.",
    )
    event_count: int = Field(
        default=0,
        ge=0,
        description="Total MarketEvents synthesised for this report.",
    )
    published_at: datetime | None = Field(
        default=None,
        description="UTC timestamp of publication. None until status=PUBLISHED.",
    )
    notion_page_id: str | None = Field(
        default=None,
        max_length=100,
        description="Notion page ID after successful publication. None until published.",
    )
    error_message: str | None = Field(
        default=None,
        max_length=2000,
        description="Error detail set when status=FAILED.",
    )

    @field_validator("coverage_date")
    @classmethod
    def _validate_coverage_date(cls, v: date) -> date:
        """Enforce coverage_date is not more than 7 days in the future."""
        today = datetime.now(tz=UTC).date()
        cutoff = today + timedelta(days=_MAX_FUTURE_COVERAGE_DAYS)
        if v > cutoff:
            raise ValueError(
                f"coverage_date must not be more than {_MAX_FUTURE_COVERAGE_DAYS} "
                f"days in the future; got {v.isoformat()!r}."
            )
        return v

    @field_validator("published_at", mode="before")
    @classmethod
    def _require_utc_published_at(cls, v: datetime | None) -> datetime | None:
        """Ensure published_at is UTC-aware when provided."""
        if v is not None and v.tzinfo is None:
            raise ValueError("published_at must be UTC-aware (tzinfo must not be None).")
        return v

    @model_validator(mode="after")
    def _validate_published_state_rules(self) -> DailyReport:
        """Enforce that published_at and notion_page_id are only set when PUBLISHED."""
        if self.status != ReportStatus.PUBLISHED:
            if self.published_at is not None:
                raise ValueError(f"published_at must be None when status={self.status!r}.")
            if self.notion_page_id is not None:
                raise ValueError(f"notion_page_id must be None when status={self.status!r}.")
        return self
