"""Public constants for the Sentinel domain contracts."""

from typing import Final

ARTICLE_TITLE_MAX_LENGTH: Final[int] = 500
ARTICLE_CONTENT_MAX_LENGTH: Final[int] = 100_000
ARTICLE_SUMMARY_MAX_LENGTH: Final[int] = 2_000
ARTICLE_ERROR_MAX_LENGTH: Final[int] = 2_000
ARTICLE_CONTENT_HASH_LENGTH: Final[int] = 64
ARTICLE_PUBLISHED_AT_MAX_FUTURE_DAYS: Final[int] = 7

MARKET_EVENT_TITLE_MAX_LENGTH: Final[int] = 300
MARKET_EVENT_SUMMARY_MIN_LENGTH: Final[int] = 100
MARKET_EVENT_SUMMARY_MAX_LENGTH: Final[int] = 2_000
MARKET_EVENT_OCCURRED_AT_MAX_FUTURE_DAYS: Final[int] = 30

SOURCE_WEIGHT_MIN: Final[float] = 0.1
SOURCE_WEIGHT_MAX: Final[float] = 2.0
SOURCE_FETCH_INTERVAL_MIN_MINUTES: Final[int] = 1
SOURCE_FETCH_INTERVAL_MAX_MINUTES: Final[int] = 1440

DAILY_REPORT_COVERAGE_DATE_MAX_FUTURE_DAYS: Final[int] = 7
DAILY_REPORT_TITLE_MAX_LENGTH: Final[int] = 300

REPORT_SECTION_TITLE_MAX_LENGTH: Final[int] = 200
REPORT_SECTION_CONTENT_MAX_LENGTH: Final[int] = 20_000

PIPELINE_ALLOWED_TRIGGERS: Final[frozenset[str]] = frozenset({"scheduler", "manual", "api"})
TASK_NAME_MAX_LENGTH: Final[int] = 200
TASK_ERROR_MAX_LENGTH: Final[int] = 5_000

__all__ = [
    "ARTICLE_CONTENT_HASH_LENGTH",
    "ARTICLE_CONTENT_MAX_LENGTH",
    "ARTICLE_ERROR_MAX_LENGTH",
    "ARTICLE_PUBLISHED_AT_MAX_FUTURE_DAYS",
    "ARTICLE_SUMMARY_MAX_LENGTH",
    "ARTICLE_TITLE_MAX_LENGTH",
    "DAILY_REPORT_COVERAGE_DATE_MAX_FUTURE_DAYS",
    "DAILY_REPORT_TITLE_MAX_LENGTH",
    "MARKET_EVENT_OCCURRED_AT_MAX_FUTURE_DAYS",
    "MARKET_EVENT_SUMMARY_MAX_LENGTH",
    "MARKET_EVENT_SUMMARY_MIN_LENGTH",
    "MARKET_EVENT_TITLE_MAX_LENGTH",
    "PIPELINE_ALLOWED_TRIGGERS",
    "REPORT_SECTION_CONTENT_MAX_LENGTH",
    "REPORT_SECTION_TITLE_MAX_LENGTH",
    "SOURCE_FETCH_INTERVAL_MAX_MINUTES",
    "SOURCE_FETCH_INTERVAL_MIN_MINUTES",
    "SOURCE_WEIGHT_MAX",
    "SOURCE_WEIGHT_MIN",
    "TASK_ERROR_MAX_LENGTH",
    "TASK_NAME_MAX_LENGTH",
]
